### ISSUE TITLE
Add Extraordinary Gems and Allow For Uncrafting

### ISSUE THREAD

**Issue by JoshWannaPaas** [JoshWannaPaas/VH2.5#1]
Originally from a1qs:
Add in the Extraordinary gem types for Larimar, Benitoite, etc, and allow Perfect and Extraordinary gems to be crafted back down after crafting them.

Method:
Would require KubeJS to add custom items or to make an additional mod for this specific purpose.

**Comment by a1qs** [comment]
added extraordinary gems in [ee384ba](https://github.com/JoshWannaPaas/VH2.5/commit/ee384babe0d376aa87621a3e984170db56a405a0)
