### ISSUE TITLE
add QOL mods

### ISSUE THREAD

**Issue by a1qs** [JoshWannaPaas/VH2.5#10]
mods can include:

- AppleSkin
- any Zoom mod
- Nature's Compass
- Jade
- Polymorph
- SophisticatedBackpacks (to be more in line with 3rd Edition)
- FancyMenu potentially 

feedback regarding these/adding others would be appreciated

**Comment by JoshWannaPaas** [comment]
Optimization mods:
Embeddium (and addons)
Lightspeed
Modernfix
Starlight x Create
Ferritecore
Lazydfu
Better FPS View Distance
RoadRunner
Connectivity
Krypton Reforged

Others:
Oculus
Shutup Experimental Settings
Explorer's Compass

I have some other ideas I'll add later

**Comment by a1qs** [comment]
backport backpacks, dunno about research if it should be split up or not, should be more expensive than danks for the higher tiers for sure, potentially limit stack upgrades to not be too overpowered
