### ISSUE TITLE
Make Challenge Crystals Co-op

### ISSUE THREAD

**Issue by JoshWannaPaas** [JoshWannaPaas/VH2.5#4]
Originally from Fae:
Making Challenge Crystals co-op? :D

Method:
Likely requires mod changes unless the challenge crystals are defined in configs, which we can change to have a co-op tag

**Comment by a1qs** [comment]
possible, easiest method would be with a custom mod to change the `ChallengeCrystalArchive` file to change the crystal type to COOP for every crystal
alternatively use kubejs or add a command which players can execute themselves

**Comment by a1qs** [comment]
needs further testing likely with a test server whether challenge crystals are coop or not by default, as the "CLASSIC" vault type may have been changed to be always coop-
