### ISSUE TITLE
More Paxel Enhancements

### ISSUE THREAD

**Issue by JoshWannaPaas** [JoshWannaPaas/VH2.5#6]
Originally from Zing:
More enhancements to paxels? I have no real ideas currently, but at least get rid of the enhancements that actually harm the paxel. I also think Paxel Charms should be a bit more expensive, excluded from loot tables, and/or be sold at the infinite soul shard vendors. Having tiered paxels may also be cool 

Method:
Hopefully config, if not, it needs an additional mod.

**Comment by a1qs** [comment]
quick glance at the config only shows config options for the weight for already available, trying to use nbt fails, so likely requires an additional mod

**Comment by a1qs** [comment]
Currently adding:
5x5 Hammer
+2 Fortune
+1 Chest Rarity
+1 Luck
+2 Luck

idk if this is a good idea
