### ISSUE TITLE
Paxel Enhancement Guarantee

### ISSUE THREAD

**Issue by JoshWannaPaas** [JoshWannaPaas/VH2.5#7]
Originally from Zing:
So, is there a way to guarantee that you craft a particular paxel charm modifier? I was thinking about maybe removing the RNG in paxel charms, and having each one be craftable with a different recipe. Fortunate being by far the most expensive, of course

Method:
Would require an additional mod

**Comment by a1qs** [comment]
added in #fb4edc1

**Comment by a1qs** [comment]
added in [fb4edc1](https://github.com/JoshWannaPaas/VH2.5/commit/fb4edc1abb87145b735257a4f337ad8ac3cccfab)
